name: Unity Tests Only

on:
  push:
    branches: [master]

jobs:
  test:
    name: Run EditMode Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Unity tests
        uses: game-ci/unity-test-runner@v2
        with:
          unityVersion: 2022.3.0f1
          testMode: EditMode
