name: Unity Android Build

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Unity Builder
        uses: game-ci/unity-builder@v2
        with:
          unityVersion: 2022.3.0f1
          targetPlatform: Android
